### ISSUE TITLE
Set logfile field of each event

### ISSUE THREAD

**Issue by imron** [scalyr/scalyr-fluentd#4]
For every event being sent, we need to add in an extra field to attrs.  We need to set the key "logfile" to the synthetic log file generated by doing /fluentd/$tag.  I know, it's wasteful to have to repeat that for every event, but we will fix this in the protocol down the road.

**Comment by imron** [comment]
Done.  If no logfile field already exists in fluent log record, then I will add a logfile field and set it to /fluentd/$tag

Note:  Not sure if this is going to be an issue, but if we are recommending clients to use scalyr.somevalue for tag names (to make it easy to have a single <match scalyr.*>) then all the logfile fields will start with scalyr, e.g. scalyr.apache-access etc.

**Comment by czerwingithub** [comment]
I think that is fine.  We could always strip out the "scalyr." before we
use it in the logfile field, but I think it will be clearer to the users
what is going on if we use the same tag that they had set in their
configuration.  The little bit of redundancy with seeing "scalyr." in the
log file names isn't that much of a distraction.

**Comment by imron** [comment]
Ok.  Will leave as is.
