### ISSUE TITLE
Memory issue after docker image update. 

### ISSUE THREAD

**Issue by tophercullen** [scalyr/scalyr-fluentd#44]
We run the `scalyr/fluentd:latest` docker image as a side-car for a few different Fargate tasks. Since the update to the docker hub image latest tag to `0.8.18` in the past 24 hours, these have all been going OOM more or less instantly on the scalyr container. Pinning everything to `0.8.17` works fine again.

One of these tasks is grossly over-provisioned in terms of memory (for CPU reasons), having something like 1gb+ more than it uses, and its still going OOM. So its seems unlikely this is an unfortunate edge case in multiple tasks with different uses, libraries, and resource allocations.

**Comment by weilliu** [comment]
@tophercullen

**Comment by tophercullen** [comment]
I am aware of the change that was made. Its why I first tried reverting to the previous image version, which again works as-is still. Clearly there are differences beyond a simple  version change, as even the resulting image sizes are substantially different.  

Reviewing the config again, the I now see there's a memory limit on the container (100mb, same as in the linked docs). Previously, I thought the scalyr container was just being subject the the overarching task resources constraints (which seemed absurd it would be hitting). 

Increasing this limit to at least 200mb appears to allow the new container version to function properly. At the documented 100mb, the current latest image (`0.8.18`) does not function properly for us. `0.8.17` works with either 100mb or 200mb.

Given the more refined nature of the  memory issue, and the documented limit published by scalyr, as I would classify this as a breaking change for this version. I recommend reverting the latest tag until such a time as the documentation can be updated, and customers notified of the new requirement.

**Comment by weilliu** [comment]
Thanks for the additional context. I just created an internal ticket for engineering to look at the issue.

**Comment by weilliu** [comment]
The engineering has reviewed the issue and confirmed that this requirement is caused by a fluentd process update. The recommended memory limit is now 300mb for running the Fargate agent.
